openapi: 3.0.0 # Indica a versão do OpenAPI sendo usada para descrever a API.

info: # Esta seção fornece informações gerais sobre a API
  title: Product API # Título da API
  description: Serviço para exibição de dados de produtos aleatórios. # Uma descrição breve do serviço oferecido pela API
  version: 1.0.0 # A versão da API

servers: # Aqui são listados os servidores nos quais a API está disponível, juntamente com suas descrições
  - url: https://api.products.com/v1 # O URL base do servidor
    description: Servidor de produção # Uma descrição do servidor
  - url: https://staging_api.products.com/v1
    description: Servidor de Staging / Teste
  - url: http://localhost:3000
    description: Servidor de desenvolvimento

tags:
  - name: Produto
    description: Dados de produtos

paths: # Esta seção descreve os endpoints da API e as operações permitidas em cada um deles
  /products: # endpoint que será documentado
    get: # verbo HTTP
      summary: Retorna uma lista de produtos # Uma breve descrição do que o endpoint faz
      tags:
        - Produto
      description: Retorna uma lista de todos os produtos disponíveis no sistema. # Uma descrição mais detalhada do endpoint
      responses: # Define as respostas possíveis para a solicitação
        '200': # número de resposta
          description: OK # texto da resposta
          content: # conteúdo esperado como resposta
            application/json: # O tipo de conteúdo da resposta
              schema: # O esquema do corpo da resposta
                type: array # tipo do retorno: array, object ...
                items: # lista de itens
                  $ref: '#/components/schemas/Product' # Referência pra o local onde estão descritos os itens
  /clients: # endpoint que será documentado
    get: # verbo HTTP
      summary: Retorna uma lista de clientes # Uma breve descrição do que o endpoint faz
      tags:
        - Cliente
      description: Retorna uma lista de todos os clientes do sistema. # Uma descrição mais detalhada do endpoint
      responses: # Define as respostas possíveis para a solicitação
        '200': # número de resposta
          description: OK # texto da resposta
          content: # conteúdo esperado como resposta
            application/json: # O tipo de conteúdo da resposta
              schema: # O esquema do corpo da resposta
                type: array # tipo do retorno: array, object ...
                items: # lista de itens
                  $ref: '#/components/schemas/Client' # Referência pra o local onde estão descritos os itens

components: # Esta seção define esquemas reutilizáveis e outros componentes da API
  schemas: # Define os componentes reutilizaveis
    Product: # Componente
      type: object # Tipo de dado
      properties: # Definição do início de uma lista
        id: # Atributo
          type: integer # Tipo de dado
          example: 1 # Valor de exemplo a ser exibido na tela
          description: Identificação do produto # Definição do atributo
        description:
          type: string
          example: Synergistic Linen Table
          description: Nome do produto
          
    Client: # Componente
      type: object # Tipo de dado
      properties: # Definição do início de uma lista
        id: # Atributo
          type: integer # Tipo de dado
          example: 1 # Valor de exemplo a ser exibido na tela
          description: Identificação do produto # Definição do atributo
        nome:
          type: string
          example: Synergistic Linen Table
          description: Nome do cliente
        sobrenome:
          type: string
          example: Synergistic Linen Table
          description: Sobrenome do cliente
        endereco:
          type: string
          example: Synergistic Linen Table
          description: Nome do cliente
